kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: transformation-admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      transformation.flow.triggermesh.io/controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: transformation-core
  labels:
    transformation.flow.triggermesh.io/controller: "true"
rules:
- apiGroups:
  - flow.triggermesh.io
  resources:
  - transformations
  - transformations/status
  verbs: &everything
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs: *everything

- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs: *everything

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Read controller configurations
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch

- apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transformation-addressable-resolver
  labels:
    duck.knative.dev/addressable: "true"
rules:
- apiGroups:
  - flow.triggermesh.io
  resources:
  - transformations
  - transformations/status
  verbs:
  - get
  - list
  - watch
